#https://www.gnu.org/software/make/manual/make.html#toc-Writing-Recipes-in-Rules
CC=gcc
CFLAGS= -Wall
LIBS= -pthread
threadedObjs= threadedVetores
seqObjs= 
all: threaded sequencial

threaded: 

	cc $(CFLAGS) -o


.PHONY clean

clean: rm -f
